# Generated by Django 5.0.2 on 2024-12-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=None)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME_APPLIANCES', 'Home Appliances'), ('WOOD', 'Wood'), ('FURNITURES', 'Furnitures'), ('SPORTS', 'Sports'), ('BOOKS', 'Books'), ('TOYS', 'Toys'), ('ELECTRONICS_ACCESSORIES', 'Electronics Accessories'), ('PHONES', 'Phones'), ('SMART_DEVICES', 'Smart Devices'), ('IRONS', 'Irons')], max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('items_quantity', models.IntegerField(default=None)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME_APPLIANCES', 'Home Appliances'), ('WOOD', 'Wood'), ('FURNITURES', 'Furnitures'), ('SPORTS', 'Sports'), ('BOOKS', 'Books'), ('TOYS', 'Toys'), ('ELECTRONICS_ACCESSORIES', 'Electronics Accessories'), ('PHONES', 'Phones'), ('SMART_DEVICES', 'Smart Devices'), ('IRONS', 'Irons')], default=None, max_length=100)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.item')),
            ],
        ),
    ]
