# Generated by Django 5.0.2 on 2024-12-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items_quantity',
            field=models.IntegerField(),
        ),
    ]
