# Generated by Django 5.0.2 on 2024-12-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0003_inventory_date_add_item_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.item'),
        ),
    ]
